version: '2'

formatters:
    enable:
        - gofmt
        - gci
    settings:
        gci:
            custom-order: true
            sections:
                - standard
                - prefix(golang.org)
                - prefix(google.golang.org)
                - prefix(github.com)
                - prefix(go.mongodb.org)
                - prefix(go.uber.org)
                - default
                - localmodule
