name: main
on:
    workflow_dispatch:
    schedule:
        - cron: '0 0 * * 0'
    push:
        branches:
            - master

jobs:
    lines:
        name: lines
        if: "!contains(github.event.head_commit.message, '[skip ci]')"
        runs-on: blacksmith-2vcpu-ubuntu-2404
        outputs:
            lines: ${{ steps.lines.outputs.lines }}
        steps:
            - name: pull repository
              uses: actions/checkout@v6
              id: repository

            - name: read lines
              id: lines
              run: |
                  echo "lines=$(jq -c 'keys' configuration/tags.json)" >> $GITHUB_OUTPUT

    deploy:
        name: ${{ matrix.line }}
        needs: [lines]
        runs-on: blacksmith-2vcpu-ubuntu-2404
        timeout-minutes: 360
        strategy:
            max-parallel: 8
            matrix:
                line: ${{ fromJSON(needs.lines.outputs.lines) }}
        steps:
            - name: pull repository
              uses: actions/checkout@v6
              id: repository

            - name: setup docker builder
              uses: docker/setup-buildx-action@v4

            - name: install go
              id: go
              uses: actions/setup-go@v6
              with:
                  go-version-file: go.mod
                  cache: false

            - name: build and push the docker container image
              id: build
              run: |
                  go run ./scripts build ${{ matrix.line }}
              env:
                  CONTAINER_REGISTRY_TOKEN: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}
                  CONTAINER_REGISTRY_USERNAME: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
                  DOCKER_REGISTRY_TOKEN: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
                  DOCKER_REGISTRY_USERNAME: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
                  QUAY_REGISTRY_TOKEN: ${{ secrets.QUAY_REGISTRY_TOKEN }}
                  QUAY_REGISTRY_USERNAME: ${{ secrets.QUAY_REGISTRY_USERNAME }}
