name: update
on:
    workflow_dispatch:
    schedule:
        - cron: '0,30 * * * *'

jobs:
    update:
        name: update
        runs-on: blacksmith-2vcpu-ubuntu-2404
        outputs:
            lines: ${{ steps.update.outputs.lines }}
        steps:
            - name: pull repository
              id: repository
              uses: actions/checkout@v6

            - name: install go
              id: go
              uses: actions/setup-go@v6
              with:
                  go-version-file: go.mod
                  cache: true

            - name: run update script
              id: update
              run: |
                  lines=$(go run ./scripts update)
                  echo "lines=$lines" >> $GITHUB_OUTPUT

            - name: commit the changes
              id: commit
              run: |
                  git config user.name 'github-actions[bot]'
                  git config user.email 'github-actions[bot]@users.noreply.github.com'

                  git add configuration/

                  if git diff --cached --quiet; then
                    echo "No changes in configuration files, skipping…"
                  else
                    git commit -m "Update configuration files [skip ci]"
                    git push origin master
                  fi

    deploy:
        name: ${{ matrix.line }}
        needs: [update]
        if: needs.update.outputs.lines != '[]'
        runs-on: blacksmith-2vcpu-ubuntu-2404
        timeout-minutes: 360
        strategy:
            max-parallel: 8
            matrix:
                line: ${{ fromJSON(needs.update.outputs.lines) }}
        steps:
            - name: pull repository
              uses: actions/checkout@v6
              id: repository

            - name: setup docker builder
              uses: docker/setup-buildx-action@v4

            - name: update repository
              id: update-repository
              run: |
                  git pull origin master

            - name: install go
              id: go
              uses: actions/setup-go@v6
              with:
                  go-version-file: go.mod
                  cache: true

            - name: build and push the docker container image
              id: build
              run: |
                  go run ./scripts build ${{ matrix.line }}
              env:
                  CONTAINER_REGISTRY_TOKEN: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}
                  CONTAINER_REGISTRY_USERNAME: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
                  DOCKER_REGISTRY_TOKEN: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
                  DOCKER_REGISTRY_USERNAME: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
                  QUAY_REGISTRY_TOKEN: ${{ secrets.QUAY_REGISTRY_TOKEN }}
                  QUAY_REGISTRY_USERNAME: ${{ secrets.QUAY_REGISTRY_USERNAME }}
